### ISSUE TITLE
WASM rust?

### ISSUE THREAD

**Issue by AGhost-7** [AGhost-7/docker-dev#52]
Bundling emscripten could be nice for the rust image :man_shrugging:

**Comment by hardy613** [comment]
Hello, 

I was thinking about his with #69, there are many language options that come with WASM, it would be interesting to have a tool to enter an image with what you need, `docker run -it aghost7/wasm-dev:bionic-deno-rust tmux new`. Doing so would add lost of images just for wasm though, so maybe a wasm tool to make an image with what devs want and they can have that image locally rather than hosting all possible wasm combinations.

**Comment by AGhost-7** [comment]
I would keep the languages split, wasm is just a target. For example I had a scala and java image, but they both target the same runtime (jvm).
